# https://circleci.com/docs/2.0/language-javascript/
version: 2.1
orbs:
  codecov: codecov/codecov@3.2.0
  cypress: cypress-io/cypress@3.1.4
jobs:
  'node-18':
    docker:
      - image: cimg/node:18
    resource_class: large
    parallelism: 1

    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable
            corepack prepare pnpm@8.7.0 --activate

      - run:
          name: Install Dependencies
          command: pnpm install --frozen-lockfile=false

      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules

      - run:
          name: Run unit test
          command: pnpm turbo run test --filter=next-api-handler

      - run:
          name: Send coverage result to Codecov
          command: pnpm turbo run cov:send --filter=next-api-handler

      - run:
          name: Verify coverages are meeting standards
          command: pnpm turbo run cov:check --filter=next-api-handler

workflows:
  version: 2
  build:
    jobs:
      - 'node-18'
      - cypress/run:
          cypress-cache-key: cypress-cache-{{ arch }}-{{ checksum "packages/next-api-handler/package.json" }}-{{ checksum "apps/example/package.json" }}
          working_directory: apps/example
          record: true
          tags: circleci
          install-command: corepack enable && corepack prepare pnpm@8.7.0 --activate && pnpm install --frozen-lockfile=false
          post-install: pnpm turbo run build --filter=example
          start-command: pnpm turbo run start --filter=example
