# https://circleci.com/docs/2.0/language-javascript/
version: 2.1
orbs:
  codecov: codecov/codecov@3.2.0
  cypress: cypress-io/cypress@2.1.0
executors:
  cypress-node:
    docker:
      - image: 'cypress/base:16.17.0'
jobs:
  'node-16':
    docker:
      - image: cimg/node:16.19.1
    resource_class: large
    parallelism: 1

    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable
            corepack prepare pnpm@latest-7 --activate

      - run:
          name: Install Dependencies
          command: pnpm install --frozen-lockfile=false

      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules

      - run:
          name: Run unit test
          command: pnpm turbo run test --filter=next-api-handler

      - run:
          name: Send coverage result to Codecov
          command: pnpm turbo run cov:send --filter=next-api-handler

      - run:
          name: Verify coverages are meeting standards
          command: pnpm turbo run cov:check --filter=next-api-handler

workflows:
  version: 2
  build:
    jobs:
      - 'node-16'
      - cypress/run:
          executor: cypress-node
          working_directory: apps/example
          record: true
          tags: circleci
          build: cd ../.. && pnpm turbo run build --filter=example
          start: cd ../.. && pnpm turbo run start --filter=example
          install-command: npm i -g pnpm && pnpm install --frozen-lockfile=false
